name: NEXT-GEN ViLi kernel 

on:
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Kernel Source
      uses: actions/checkout@v4

    - name: Set up Build Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y bc bison build-essential curl flex git libssl-dev libncurses5-dev python3 zip unzip tzdata
        sudo apt-get install -y gcc-aarch64-linux-gnu
        sudo apt-get install -y gcc-arm-linux-gnueabi

    - name: Patch Drivers for Clang Compatibility
      run: |
        # Fix 1: Resolves the Wi-Fi driver type conflict error
        sed -i 's/unsigned char \*data, long unsigned int data_len/unsigned char *data, size_t data_len/g' drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_cfg80211.c

        # Fix 2: Convert ALL variations of the cdsprm enums to plain integers to stop function mismatches
        sed -i 's/enum sysmon_cdsp_feature_compute_prio_idx/int/g' drivers/soc/qcom/cdsprm.c include/linux/soc/qcom/cdsprm_cxlimit.h
        sed -i 's/enum cdsprm_compute_priority/int/g' drivers/soc/qcom/cdsprm.c include/linux/soc/qcom/cdsprm_cxlimit.h
        sed -i '1s/^/#define CDSPRM_COMPUTE_AIX_OVER_HVX 3\n/' include/linux/soc/qcom/cdsprm_cxlimit.h

    - name: Build Kernel
      run: |
          export ARCH=arm64
          export SUBARCH=arm64
          export HEADER_ARCH=arm64
          
          # Hook directly into your pre-installed system compilers
          export CC=clang
          export CLANG_TRIPLE=aarch64-linux-gnu-
          export CROSS_COMPILE=aarch64-linux-gnu-
          export CROSS_COMPILE_ARM32=arm-linux-gnueabi-
          
          # Configure the kernel profile config
          make O=out vili_defconfig
          
          # Run compilation process with strict driver error bypassing
          make -j$(nproc --all) O=out KCFLAGS="-Wno-error"
          
    - name: Package with AnyKernel3
      run: |
          wget https://github.com -O ak3.zip
          unzip ak3.zip && mv AnyKernel3-master AnyKernel3 && cp out/arch/arm64/boot/Image AnyKernel3/

          
          cd AnyKernel3
          sed -i 's/do.devicecheck=1/do.devicecheck=0/g' anykernel.sh
          
          zip -r9 ../HyperOS-Vili-Kernel.zip * -x .git* README.md
    - name: Upload Flashable Kernel Zip
      uses: actions/upload-artifact@v4
      with:
        name: HyperOS-Vili-Kernel
        path: ./HyperOS-Vili-Kernel.zip
        
